---
title: "3. Descriptive Statistics. Parametric and No Parametric, Linear Regression, among others"
subtitle: "R Basic Course IEO"
author: "Mardones, M; Zúñiga. MJ"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
bibliography: Course_R_IEO.bib
csl: apa.csl
link-citations: yes
linkcolor: blue
output:
  html_document:
    keep_md: true
    toc: true
    toc_deep: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
    theme: cosmo
    fontsize: 0.9em
    linestretch: 1.7
    html-math-method: katex
    self-contained: true
    code-tools: true
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup1, echo=FALSE}
#rm(list = ls())
#set.seed(999)
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.height = 3,
                      fig.width = 5,
                      fig.align = 'center',
                      fig.pos = "H",
                      dev = 'jpeg',
                      dpi = 300,
                      tidy.opts=list(width.cutoff=50), 
                      tidy=TRUE)
```


Sources in this [link](https://cienciadedatos.net/estadistica-con-r)

[here](https://www.datanalytics.com/libro_r/index.html)


[Data Types & Probability Distributions](https://fcorowe.github.io/sl/d1n1_intro.html)

LR model with [ggPredict()](https://cran.r-project.org/web/packages/ggiraphExtra/vignettes/ggPredict.html)

```{r}
data("iris")
iris
```

```{r}
# What is the mean age?
mean(pirates$age)
## [1] 27

# What was the tallest pirate?
max(pirates$height)
## [1] 209

# How many pirates are there of each sex?
table(pirates$sex)
## 
## female   male  other 
##    464    490     46
```

